config:
  aws:region: ap-south-1
  sales-intel-infra:appName: sales-intel
  sales-intel-infra:environment: dev
  sales-intel-infra:geminiModel: gemini-3.1-flash-lite
  sales-intel-infra:geminiApiKey:
    secure: v1:pXmTXgg0tJ9/eoeN:jAxiWTqxU720RxsIlyC4jLYl0F/cKrhqeub63geQk5J6yk8Tsijo11av6tt6lNb1qXU0a8D6RszygJtQ+Ifn5FBGvGmm
  sales-intel-infra:logfireToken:
    secure: v1:mT4aVqyOi0aGkIDE:VUay+3kPimhp+HV2AKMC8Kp8TdguF+BAmsuaSWgb3hAueadlV6zXW/lhiYjL8rYzkUh4dOFAp1qEutMTJeCMer9GI7C11pw=
encryptionsalt: v1:nIrUaEpw+Z4=:v1:xm7JeQb3duOAbzcU:N+fCd3EzfLHh2gG0RRptPKuoNZp4xQ==
