from typing import Any, List, Optional, Protocol, Tuple, runtime_checkable

from src.services.jobs.types import (
    CompleteJobCommand,
    CreateJobCommand,
    CreateJobRequest,
    JobDetail,
    JobHandlerFunc,
    JobListQuery,
    JobSummary,
    SubmitJobCommand,
    UpdateProgressCommand,
)



@runtime_checkable
class IJobDispatcher(Protocol):
    def dispatch(self, job_id: str, job_type: str) -> None: ...


@runtime_checkable
class IJobsReader(Protocol):
    def get_job(self, job_id: str) -> Optional[JobDetail]: ...

    def list_jobs(self, query: JobListQuery) -> Tuple[List[JobSummary], int]: ...


@runtime_checkable
class IJobsWriter(Protocol):
    def create_job(self, command: CreateJobCommand) -> str: ...

    def start_job(self, job_id: str) -> bool: ...

    def update_status(self, job_id: str, status: Any) -> None: ...

    def update_progress(self, command: UpdateProgressCommand) -> bool: ...

    def complete_job(self, command: CompleteJobCommand) -> bool: ...

    def fail_job(self, job_id: str, error_message: str) -> bool: ...

    def increment_retry(self, job_id: str) -> int: ...

    def recover_stale_jobs(self, stale_threshold_seconds: Optional[int] = None) -> int: ...


@runtime_checkable
class IJobsService(Protocol):
    def register_handler(self, job_type: str, handler: JobHandlerFunc) -> None: ...

    def submit_job(self, command: SubmitJobCommand) -> str: ...

    def create_job(self, request: CreateJobRequest) -> JobDetail: ...

    def execute_job(self, job_id: str) -> None: ...

    def get_job(self, job_id: str) -> Optional[JobDetail]: ...

    def list_jobs(self, query: JobListQuery) -> Tuple[List[JobSummary], int]: ...

    def retry_job(self, job_id: str, auto_start: bool = True) -> str: ...

    def cancel_job(self, job_id: str) -> None: ...

    def update_job_progress(self, command: UpdateProgressCommand, status: Optional[Any] = None) -> None: ...

    def complete_job(self, command: CompleteJobCommand) -> None: ...

    def fail_job(self, job_id: str, error: str) -> None: ...

    def recover_stale_jobs(self, stale_threshold_seconds: Optional[int] = None) -> int: ...
