
from typing import Dict, List, Optional, Protocol, Tuple

from src.services.accounts.types import Account, SecuritySignal


class IAggregatorService(Protocol):

    def resolve_account_keys(self, record: dict) -> List[str]: ...

    def get_asset_id(self, features: dict) -> Optional[Tuple[Optional[str], Optional[int], Optional[str]]]: ...

    def extract_vulnerability_features(self, vulns: Optional[dict]) -> dict: ...

    def extract_features(self, record: dict) -> dict: ...

    def detect_signals(self, features: dict) -> List[SecuritySignal]: ...

    def process_record(
        self, record: dict
    ) -> Tuple[List[str], Optional[Tuple[Optional[str], Optional[int], Optional[str]]], List[SecuritySignal]]: ...

    def aggregate(self, records: List[dict]) -> List[Account]: ...

    def build_accounts(self, records: List[dict]) -> Dict[str, Account]: ...

    def load_accounts_from_jsonl(self, jsonl_path: str, limit: Optional[int] = None) -> Dict[str, Account]: ...
